name: Dependency Check

concurrency:
  group: rust-dependency-check-${{ github.head_ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron:  '0 0 * * *'
  pull_request:

jobs:
  update_dependency:
    name: Check dependency
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Update dependency
        run: nix develop -c 'update-dependency'

      - uses: actions/checkout@v3

      - name: Commit
        run: |
          git config user.name 'Antonio Yang'
          git config user.email 'yanganto@gmail.com'
          git add Cargo.toml
          git commit -m "Update dependency"

      - uses: peter-evans/create-pull-request@v4
        with:
          reviewers: yanganto
